services:
    mysql:
        image: mysql
        container_name: egargo.mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            TZ: Asia/Manila
        ports:
            - 3306:3306
        volumes:
            - egargo-mysql-data:/var/lib/mysql

    postgres:
        image: postgres
        container_name: egargo.postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - egargo-postgres-data:/var/lib/postgresql

    adminer:
        image: adminer
        container_name: egargo.adminer
        restart: always
        environment:
            ADMINER_DESIGN: nette
        ports:
            - 8080:8080
        depends_on:
            - mysql
            - postgres

volumes:
    egargo-mysql-data:
    egargo-postgres-data:
